export const LOAD_MOVIES_REQUEST = 'LOAD_MOVIES_REQUEST'
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE'

export const LOAD_MORE_MOVIES_REQUEST = 'LOAD_MORE_MOVIES_REQUEST'
export const LOAD_MORE_MOVIES_SUCCESS = 'LOAD_MORE_MOVIES_SUCCESS'
export const LOAD_MORE_MOVIES_FAILURE = 'LOAD_MORE_MOVIES_FAILURE'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'